### ISSUE TITLE
Python Import Errors

### ISSUE THREAD

**Issue by vlasp** [fastlib/fCWT#18]
I installed fCWT using pip, but when I try to run the tutorial Jupyter notebook I get an import error. This is on Python 3.10.4.

![image](https://user-images.githubusercontent.com/3680642/212788109-42c7c93a-765b-4d9b-8986-1d3e8d09d11b.png)

**Comment by fastlib** [comment]
I see the error indeed arises when on windows. I will try to fix it. 

For now, a quick fix would be to go to the fCWT package location in the site-packages folder and move all files inside the 'fCWT/libs' folder to the root 'fCWT' package folder. This should fix the linkage error for now.

**Comment by fastlib** [comment]
Fixed
