### ISSUE TITLE
fCWT application question

### ISSUE THREAD

**Issue by sunshineinsandiego** [fastlib/fCWT#2]
Hi - I read your paper in Nature, and I'm hoping you might be able to answer a few quick questions about the real-time aspect of fCWT. 
- When calculating the power of specific frequency bands in your EEG data, for example, how did you mimic a real-time, streaming application?  Did you use fCWT to analyze chunks of data (i.e. 0.5s) so that the time-resolution of the power spectrum was actually 0.5s? Or did you build the time-frequency analysis in real time by computing the WT on incoming samples?
- Have you used fCWT for real-time, on-line applications to get instantaneous psd's?

Thanks!

**Comment by fastlib** [comment]
Hi, thans for your questions! 

- For each dataset and sampling rate, we calculated the Realtime Analysis Ratio (RAR) which is the ratio between the signal's time span and duration of computation. With a RAR < 1 the computation is faster than the signal's duration which means that real-time analysis is within reach. Currently, fCWT is not yet programmed to work with datastreams. However, fCWT can be easily adapted to that application if a signal is split up into chunks that are just wide enough to encapsulate the lowest frequency one wants to measure (i.e., a 10Hz signal requires a window size of 0.1s and a 0.5 Hz signal needs a window of 2s). Each chunk is analysed by fCWT. As this analysis is much faster than the chunk's duration, one obtains real-time performance. Fortunately, this does not decrease time-resolution as you say. Within each chunk, the time-resolution is still at the per-sample level as would be in offline research. You could even dynamically adapt the chunk length to each scale to reduce unnecessary latency in the high-resolution spectrum. 
- The application of fCWT to real-world on-line applications would be a great topic for future research!

I hope I have answered your questions.

**Comment by sunshineinsandiego** [comment]
Yes, perfectly! Thank you

**Comment by stellarpower** [comment]
So, to confirm - the implementation is only realtime/online in the sense that it is fast enough to be called repeatedly? It doesn't keep some sort of internal state and recalculate when I e.g. push it a sample or small packet of samples, I would need to implement a sliding window myself, and call the function repeatedly over that window?
