### ISSUE TITLE
fCWT matlab for window

### ISSUE THREAD

**Issue by kingg0218** [fastlib/fCWT#22]
Hi

I'm trying to build MEX-file from source but I'm stuck on a problem
I installed Cmake and GCC, so I made it through until [$ cmake ../ -DBUILD_MATLAB=ON]
But when I type [make] after that, it says this and I cannot find MEX file
**make: *** No targets specified and no makefile found.  Stop.**

Can you spot the problem in this situation?

![image](https://user-images.githubusercontent.com/24986714/217283243-a64a195a-5fc7-4497-9377-4b0f65a5ede6.png)
These are the contents in 'build' file

**Comment by DiellorBasha** [comment]
Hi
I am also experiencing the same issue. 
I installed Cmake and Microsoft Visual C++ but when I try to build from source using "make", I get: 
**make: *** No targets specified and no makefile found. Stop.**

Could you please advise on a possible solution?

**Comment by whip123** [comment]
Hi, I also have encountered this issue, is there any update on this?

**Comment by felixdollack** [comment]
@kingg0218, @DiellorBasha and @whip123

Instead of calling `make`, can you try calling `cmake build .` ?

**Comment by whip123** [comment]
Not sure if correct or not, but I'm able to get the 2 mex file in fCWT\build\Debug using the same method

![image](https://user-images.githubusercontent.com/86820294/226254215-a13fbbf3-2e27-42fc-a6f3-f1cecedc2cf8.png)

**Comment by felixdollack** [comment]
@whip123, do the Mex files work if you put them in your Matlab path?

**Comment by whip123** [comment]
Yeah I believe so, after adding the 2 mex file, im able to run the example.mlx 
![image](https://user-images.githubusercontent.com/86820294/226349949-63926890-8c0d-4053-bdea-3a77a6514615.png)

**Comment by Ana-bitsensing** [comment]
cmake . -B_build -G "Visual Studio xx 20xx Win64"
Of course a Win32 build will look for a Win32 Matlab Version. However instead of saying Could NOT find Matlab, the FindMatlab.cmake Script could be improved to give a WARNING such as "Compiling for 32bit, but only 64bit Matlab Version is installed"

https://cmake.org/Bug/view.php?id=15786

**Comment by CrovaS** [comment]
@felixdollack I have this issue, but I can't build the fCWT.sln file with visual studio because there's an error that visual studio can't find OpenMP. I wonder if there are any additional modifications to the CMakeLists.txt file.
Is it okay to ask for help in this regard?

**Comment by CrovaS** [comment]
It has been resolved. Thank you.
