### ISSUE TITLE
I can't install fCWT

### ISSUE THREAD

**Issue by poncev** [fastlib/fCWT#24]
I want to install fCWT in Ubuntu 20.04 for C++, but when I "make" the library, I get

> [ 60%] Linking CXX executable fCWT_example
> /usr/bin/ld: attempted static link of dynamic object `../libs/libfftw3fl.so'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/fCWT_example.dir/build.make:101: fCWT_example] Error 1
> make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/fCWT_example.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

The file "../libs/libfftw3fl.so" exists, so I am clueless about this.

Thank you for writing this library!

**Comment by fastlib** [comment]
Not sure what is happening here, but will test it on my Ubuntu 20.04 machine to see if I can replicate your error soon.

**Comment by fastlib** [comment]
Fixed in the current version! The issue was with the "-Wl,no_compact_unwind" flag that was added to hide warning messages. This works on Mac and Windows, but it seems to fail on Ubuntu due to it forcing libraries to be statically loaded. I removed this flag.
