### ISSUE TITLE
Can not run with numpy 1.22.4

### ISSUE THREAD

**Issue by pty819** [fastlib/fCWT#28]
environment： win11 numpy installed with mambaforge， numpy version 1.22.4

RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_29484\3900396640.py](https://file+.vscode-resource.vscode-cdn.net/d%3A/0112liucheng/~/AppData/Local/Temp/ipykernel_29484/3900396640.py) in 
----> 1 import fcwt

[c:\Users\Administrator\mambaforge\lib\site-packages\fcwt\__init__.py](file:///C:/Users/Administrator/mambaforge/lib/site-packages/fcwt/__init__.py) in 
----> 1 from .fcwt import Morlet, Scales, FCWT, FCWT_LINSCALES, FCWT_LOGSCALES, FCWT_LINFREQS
      2 from .boilerplate import cwt, plot
      3 

[c:\Users\Administrator\mambaforge\lib\site-packages\fcwt\fcwt.py](file:///C:/Users/Administrator/mambaforge/lib/site-packages/fcwt/fcwt.py) in 
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _fcwt
     14 else:
     15     import _fcwt

ImportError: numpy.core.multiarray failed to import

can you please update the API version？

**Comment by fastlib** [comment]
I will look into it!

**Comment by fastlib** [comment]
I could only reproduce this error when I downgraded my numpy version from 1.24/1.23 to 1.22.4. Consequently, the error should be gone when you upgrade your numpy installation to 1.23 or 1.24. Can you confirm?
