### ISSUE TITLE
How to get the output time–frequency array?

### ISSUE THREAD

**Issue by Tokenmw** [fastlib/fCWT#3]
Hi, your work is excellent. I have some questions about how to get the output time-frequency arrays?  Because I want to plot the time-frequency plot obtained by fCWT.  Can you give me some specific advice or specific examples? Thanks.

**Comment by fastlib** [comment]
Hi Tokenmw,

The example shown at fCWT's repository home page shows an easy application of fCWT. The output matrix is saved to the 'tfm' vector of floats. This vector contains the complex time-frequency matrix with the real and complex components interleaved. This means that even elements correspond to real and uneven to complex components. I hope this answers your question.

Kind regards

**Comment by Tokenmw** [comment]
My C++ level is a bit low. I compiled and executed the program according to the code provided by your repository, and successfully output the running time and average value on the cmd terminal. But I'm not quite sure how to save the time-frequency array obtained after fCWT transformation to my computer. Hope to get more specific help from you. Thank you.

**Comment by Tokenmw** [comment]
I seem to know how to do it, thanks.

**Comment by somewayin** [comment]
> The example shown at fCWT's repository home page shows an easy application of fCWT. The output matrix is saved to the 'tfm' vector of floats. This vector contains the complex time-frequency matrix with the real and complex components interleaved. This means that even elements correspond to real and uneven to complex components. I hope this answers your question.

please,could you tell me how to do it?Thanks!
