### ISSUE TITLE
Benchmark against CCWT

### ISSUE THREAD

**Issue by Lichtso** [fastlib/fCWT#6]
Hi, seems like you kind of reinvented [CCWT](https://github.com/lichtso/CCWT). Same idea: Transform signal to frequency domain using FFT, do a convolution with a wavelet per frequency band via element wise multiplication, and transform each frequency band back using iFFT.

More implementations are nice, and so would be to have a comparison between the two.

**Comment by fastlib** [comment]
Hi Lichtso, thanks for mentioning CCWT. I did not yet come across that repository. I will add it to the benchmark soon! The more CWT implementations are added to the benchmark, the better.

**Comment by fastlib** [comment]
CCWT is added to the benchmark. Thank you for noting it.
