### ISSUE TITLE
fCWT on ARM Cortex M7 or so?

### ISSUE THREAD

**Issue by karu2003** [fastlib/fCWT#64]
There are prototypes of functions, but there are no functions themselves. Are you planning to publish them?

void convolve(float* in, complex<float> *out, Wavelet *wav, float scale);
void firbased(float* in, float *out, Wavelet *wav, float scale);

**Comment by guiminlongmiao-arch** [comment]
Hi，Did you succeed? I also want to try to use fcwt on edge devices, but I don’t know how to start

**Comment by karu2003** [comment]
Hi, I got it working. I use it to decode signals on Coral. It's somewhere in my repository.
