### ISSUE TITLE
Linking problem while doing make

### ISSUE THREAD

**Issue by amol2891** [fastlib/fCWT#7]
Greetings,

I am unable to compile the code. After CMake if I do the Make then I am getting following errors [OpenSuse Tumbleweed, g++11]. Please help to get is started. I already modified the CMakeList.txt file to include g++11.
 
[ 14%] Building CXX object CMakeFiles/fCWT.dir/src/fcwt.cpp.o
[ 28%] Linking CXX shared library libfCWT.so
[ 28%] Built target fCWT
[ 42%] Building CXX object CMakeFiles/fCWT_example.dir/src/fcwt.cpp.o
[ 57%] Building CXX object CMakeFiles/fCWT_example.dir/src/main.cpp.o
[ 71%] Building CXX object CMakeFiles/fCWT_example.dir/src/rwave.cpp.o
[ 85%] Building CXX object CMakeFiles/fCWT_example.dir/src/wavelib.cpp.o
[100%] Linking CXX executable fCWT_example
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fCWT_example.dir/src/fcwt.cpp.o: in function `fcwt::create_optimization_schemes(int, int, int)':
fcwt.cpp:(.text+0x2b5): undefined reference to `fftwf_init_threads'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x2c1): undefined reference to `fftwf_plan_with_nthreads'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x341): undefined reference to `fftwf_plan_dft_r2c_1d'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x3b1): undefined reference to `fftwf_plan_dft_1d'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x3bb): undefined reference to `fftwf_export_wisdom_to_filename'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x3cb): undefined reference to `fftwf_free'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x3d3): undefined reference to `fftwf_free'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x476): undefined reference to `fftwf_alloc_complex'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text+0x481): undefined reference to `fftwf_alloc_complex'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fCWT_example.dir/src/fcwt.cpp.o: in function `fcwt::load_optimization_schemes(bool, int, int)':
fcwt.cpp:(.text+0x6b4): undefined reference to `fftwf_import_wisdom_from_filename'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fCWT_example.dir/src/fcwt.cpp.o: in function `fcwt::main(float*, float*, int*, int*, int*, int*, float*, int, bool)':
fcwt.cpp:(.text.startup+0xc1): undefined reference to `fftwf_alloc_complex'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0xce): undefined reference to `fftwf_alloc_complex'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x121): undefined reference to `fftwf_init_threads'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x12d): undefined reference to `fftwf_plan_with_nthreads'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x15b): undefined reference to `fftwf_plan_dft_r2c_1d'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x166): undefined reference to `fftwf_execute'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x16e): undefined reference to `fftwf_destroy_plan'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x18c): undefined reference to `fftwf_plan_dft_1d'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x2a8): undefined reference to `fftwf_execute_dft'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x2e4): undefined reference to `fftwf_destroy_plan'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x2ec): undefined reference to `fftwf_free'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x2f4): undefined reference to `fftwf_free'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: fcwt.cpp:(.text.startup+0x2f9): undefined reference to `fftwf_cleanup_threads'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/fCWT_example.dir/src/wavelib.cpp.o: in function `wavelib::cwt(double*, int, int, int)':
wavelib.cpp:(.text+0x28): undefined reference to `cwt_init'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: wavelib.cpp:(.text+0x59): undefined reference to `setCWTScales'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: wavelib.cpp:(.text+0x64): undefined reference to `cwt'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: wavelib.cpp:(.text+0x70): undefined reference to `cwt_free'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fCWT_example.dir/build.make:148: fCWT_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/fCWT_example.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by amol2891** [comment]
Installation issue sorted out.

**Comment by ScherbakovAl** [comment]
I have the same problem. I'm under ubuntu. What did you do to fix this problem?
