### ISSUE TITLE
Example Code giving Segmentation Fault

### ISSUE THREAD

**Issue by amol2891** [fastlib/fCWT#8]
Greetings, 

I was able to successfully install the fCWT but the example given on the home page was compiled using 

$ g++ -mavx2 -fopenmp -lfCWT ./example.cpp 

compilation successful but,

$ ./a.out 
Segmentation fault (core dumped)

Please help.

**Comment by fastlib** [comment]
Probably fixed in current version.

**Comment by felixdollack** [comment]
I cloned the current version and followed the instructions in the readme to generate a project file for Visual Studio 2022.
Running the example on Windows 11 ends with a segfault as well.

It crashes in line 471 of main.cpp
```
Exception thrown at 0x00007FFE24736D78 (fftw3f.dll) in fCWT_example.exe:
0xC0000005: Access violation reading location 0x0000016A00226170.
```
